### ISSUE TITLE
genome build option for LD

### ISSUE THREAD

**Issue by nnishiyama** [myles-lewis/locuszoomr#13]
Any chance you can include an option in the ```link_LD()``` function to choose the genome build as LDlinkR now supports multiple builds? Thanks!

**Comment by myles-lewis** [comment]
Hi nnishiyama,

Good suggestion. I have added `...` to `link_LD()` to allow passing of arguments through to LDlinkR function `LDmatrix()`. So now you can add the argument `genome_build` to the `link_LD()` call.

Bw, Myles

**Comment by myles-lewis** [comment]
Hi nnishiyama,

Just to warn you that I have just pushed another update to locuszoomr main branch to rename the `LDtoken` argument to `token`. It's shorter, simpler and more consistent with all the other LDlinkR arguments. So you'll need to update your calls to `link_LD()` when using the latest version.

Bw, Myles

**Comment by nnishiyama** [comment]
Fantastic. Thanks for the heads up!
