### ISSUE TITLE
Citing package

### ISSUE THREAD

**Issue by omarelgarwany** [myles-lewis/locuszoomr#22]
Hi thanks very much for developing this packages. It's helped me with both my thesis and manuscripts. I was wondering how can one reference it in a publication. I can't see anything here or in the vignette.

**Comment by myles-lewis** [comment]
Hi omarelgarwany,

I'm working on a short paper which we plan to submit, but haven't got round to finishing it just yet. I think the best way to cite the package for the moment until the paper comes out is in standard R package format. Something like:

Lewis MJ, Wang S (2024) locuszoomr: Publication-Ready Gene Locus Plots with Gene Annotations. R package version 0.3.0. https://cran.r-project.org/package=locuszoomr

Bw,
Myles
