### ISSUE TITLE
gg_scatter does not plot points correctly when beta is provided

### ISSUE THREAD

**Issue by danwestern** [myles-lewis/locuszoomr#25]
Hi @myles-lewis ,

Thanks for putting together a really wonderful package that makes customizing these plots so much easier.

I am attempting to plot QTL data in a stacked format using gg_scatter() and plot_grid() and came across a potential issue when trying to use the beta to plot effect direction. It seems that when all of the significant variants have a negative beta, the shape is set incorrectly to match the shape used for positive beta.

Here's a screenshot from the 'data' dataframe in my locus object, with the most significant variants that I am looking at:
![image](https://github.com/user-attachments/assets/00ae12fa-6f83-4978-9215-00879f1d1b64)

The top two variants are significant, and both have a negative beta. However, when I use gg_scatter() to plot them, this is the output:
![image](https://github.com/user-attachments/assets/14cfc8af-f583-41cf-bada-97829e5fc87f)

The shapes are plotted as expected when using scatter_plot():
![image](https://github.com/user-attachments/assets/2198740d-a8e2-46b9-ab9c-03ad23ccebb3)

If I can provide more detail please let me know, thanks again.

**Comment by myles-lewis** [comment]
Hi @danwestern ,

I just pushed a fix for this. Thanks for spotting this. It's to do with breaks needing to be specified in ggplot2. Otherwise the factor drops missing levels. It should work now. Do you want to install the GitHub version and try it out and let me know if it's fixed. Thanks.

Bw, Myles

**Comment by danwestern** [comment]
Hello again,

Everything looks great with the change! Thanks for the quick response and fix.

-Dan
