### ISSUE TITLE
Direct input of minus log10 pvalues

### ISSUE THREAD

**Issue by sahirbhatnagar** [myles-lewis/locuszoomr#31]
Is there a way to directly provide -log10(p-values) instead of p-values to the locus plot functions? The motivation is to allow plotting p-values that exceed the minimum float allowed by R.

**Comment by myles-lewis** [comment]
Yes that should be straightforward. Just provide your column of y axis values in your dataframe and set the argument `yvar` to that column name when calling `locus()`. You can set the y axis title manually using `ylab` when calling `locus_plot()`.
